import turtle
turtle.showturtle()
turtle.setup(400,100)
turtle.color("black")
turtle.pensize(10)
turtle.penup()
turtle.setpos(20,-66)
turtle.pendown()
turtle.circle(80)
turtle.setup(100,100)
turtle.penup()
turtle.setpos(180,-66)
turtle.pendown()
turtle.circle(80)
turtle.penup()
turtle.setpos(150,85)
turtle.pendown()
turtle.left(90)
turtle.forward (300)
turtle.circle(50,180)
turtle.forward(300)
turtle.penup()
turtle.pencolor("black")
turtle.setpos(100,427)
turtle.pendown()
turtle.forward(30)
turtle.left(90)
turtle.pencolor("black")
turtle.pensize(8)
turtle.forward (50)
turtle.left (180)
turtle.forward (100)
